import {receipt,fieldSnapshot,doctorTask,doctorReply} from './audit.js';
import {providers,makeSlots,insuranceTool,conversationAdapter as language} from './adapters.js';
export {providers};
export const names={insurance:'保险优先咨询',common:'常见运动损伤',review:'不确定疾病审核',postop:'术后 / 转诊康复',provider:'指定医生 / PT',postvisit:'看诊后授权'};
export const labels={part:'不适部位',duration:'病程',treatment:'既往治疗',wish:'期望时间',history:'病史与当前问题',documents:'病历 / 影像资料',surgeryDate:'手术日期',procedure:'术式',provider:'指定医生 / PT',company:'保险公司',plan:'保险计划',member:'会员编号',extra:'医生要求补充资料',visitNote:'本次看诊病历',imaging:'影像检查',imagingSite:'影像部位',rehabApplicant:'康复申请人',rehabVisits:'申请康复次数',rehabPlan:'康复治疗计划',authorizationExtra:'授权补充资料'};
export const requirements={insurance:[],common:['part','duration','treatment','wish'],review:['history','documents','wish'],postop:['surgeryDate','procedure','documents','history','wish'],provider:['provider','history','wish'],postvisit:['visitNote','imaging','imagingSite','rehabApplicant','rehabVisits','rehabPlan','company','plan','member']};
export const initial=()=>({cases:[],slots:makeSlots(),selected:null});
export function event(c,text){c.events.push({time:new Date().toLocaleTimeString('zh-CN'),text});}
export function say(c,text,role='agent'){c.messages.push({role,text});if(role!=='patient')receipt(c,'message',role==='staff'?'人工回复患者':'Agent 回复患者',role==='staff'?c.owner:'Front Desk AI',c.name+' · 原会话',{会话ID:c.id,消息:text},{发送:'已显示在本地患者会话',消息序号:c.messages.length});}
export function create(db){const c={id:crypto.randomUUID(),number:db.cases.length+1,name:`体验患者 ${String(db.cases.length+1).padStart(2,'0')}`,intent:null,fields:{},status:'AI处理中',stage:'intro',owner:'Front Desk AI',messages:[],events:[],insurance:false,eligibility:null,review:null,human:false,risk:false,appointment:null};db.cases.unshift(c);db.selected=c.id;say(c,'您好，欢迎来到跃动运动医学。请告诉我您的就诊需求，我会协助收集资料、联系医疗人员和安排预约。');event(c,'会话创建 → 等待患者描述需求');return c;}
export function missing(c){if(c.insuranceFirst&&!c.visitConfirmed)return ['company','plan','member'].filter(k=>!c.fields[k]);if(!c.intent)return ['就诊需求'];return [...requirements[c.intent],...(c.insurance?['company','plan','member']:[]),...(c.review==='supplement'?['extra']:[])].filter(k=>!c.fields[k]);}
export function advance(c){if(c.human||c.risk||c.stage==='closed')return;
 const need=missing(c);if(need.length){c.stage='collect';c.status='AI处理中';c.owner='Front Desk AI';c.awaiting=need[0];say(c,`请补充${labels[c.awaiting]}。${c.awaiting==='documents'?'可使用下方“添加模拟病历”，或文字说明现有资料。':''}`);event(c,`缺少${labels[c.awaiting]} → 请求补充`);return;}
 if(c.insuranceFirst&&!c.visitConfirmed){if(checkInsurance(c))return;c.stage='insurance-decision';c.status='等待患者决定';c.owner='患者';say(c,`保险查询已返回：${c.eligibility==='selfpay'?'已选择自费':'模拟可覆盖'}。您想继续了解就诊并预约，还是暂时只了解保险？在您决定前，我不会安排预约。`);event(c,'保险结果先回到患者 → 等待是否就诊的明确决定');return;}
 if(c.intent==='postvisit'){startAuthorization(c);return;}
 if(['postop','review'].includes(c.intent)&&c.review!=='accepted'){c.stage='review';c.review='pending';c.status='等待医生确认';c.owner='医疗审核组';say(c,'资料已提交医生 / 医导审核。审核结果会回到本会话，确认后再安排预约。');event(c,'资料收集完成 → 创建医疗审核任务');doctorTask(c);return;}
 if(checkInsurance(c))return;
 c.stage='slots';c.status='AI处理中';c.owner='Front Desk AI';say(c,`预约前置条件已满足。${c.insurance?'费用方式：'+(c.eligibility==='selfpay'?'自费':'模拟可覆盖')+'。':''}请在下方选择人员和可用时段；期望时间仅作偏好，最终以您选择的时段为准。`);event(c,'审核 / 支付条件满足 → 查询 Mock 排班');}
export function receive(c,text){text=text.trim();if(!text)return;say(c,text,'patient');
 if(language.isRisk(text)||language.isComplaint(text)){c.risk=c.risk||language.isRisk(text);c.human=true;c.status='等待人工';c.owner=c.risk?'医疗人员':'人工客服';receipt(c,'human',c.risk?'优先医疗协作任务':'人工客服任务','Front Desk AI',c.owner,{触发消息:text,...fieldSnapshot(c)},{送达:'本地模拟工作台',处理:'等待责任人处理',自动预约:'暂停'},'waiting');event(c,c.risk?'高风险关键词命中 → 暂停自动预约 → 医疗人员接管':'投诉 / 人工请求 → 人工接管');say(c,c.risk?'已暂停自动预约并标记为优先医疗处理。请及时联系手术团队；如情况紧急，请立即联系当地急救服务。此演示不会实际通知医生。':'已转人工客服，AI 暂停自动回复。');return;}
 if(c.human){event(c,'患者新消息 → 保留在人工会话，AI 不回复');return;}
 if(c.intent==='postvisit'&&/申请结果|保险.*(批准|批复|回来|结果)|授权.*(状态|结果)|到哪一步/.test(text)){reportAuthorizationStatus(c);return;} if(c.stage==='closed'){say(c,'本次服务已结束。您可以新建会话发起新的需求。');return;}
 if(c.stage==='insurance-decision'){if(/暂不|不预约|只了解|先不了|不看/.test(text)){decideVisit(c,false);return;}if(/继续|预约|看诊|就诊/.test(text)){decideVisit(c,true);return;}say(c,'您可以选择“继续了解并预约”或“暂不就诊”。');return;}
 if(!c.intent){c.intent=language.classify(text);c.insurance=c.insurance||/保险|aetna|bupa|cigna/i.test(text);if(c.intent==='postvisit')c.insurance=true;c.insuranceFirst=c.insuranceFirst||(/先.*保险|保险.*再.*(决定|看|约)/.test(text));if(c.insuranceFirst&&!c.visitConfirmed)c.intent='insurance';if(/aetna/i.test(text))c.fields.company='Aetna';if(/bupa/i.test(text))c.fields.company='Bupa';if(/cigna/i.test(text))c.fields.company='Cigna';if(/陈晨/.test(text))c.fields.provider='陈晨 PT';if(/林悦/.test(text))c.fields.provider='林悦医生';event(c,`识别为${names[c.intent]}${c.insurance?' + 保险核验':''}`);advance(c);return;}
 if(c.stage==='collect'){if(c.awaiting==='provider'&&!providers.some(p=>p.name===text)){say(c,'请选择：林悦医生、陈晨 PT 或周宁 PT。');return;}if(c.awaiting==='surgeryDate'&&(!/^\d{4}-\d{2}-\d{2}$/.test(text)||!Number.isFinite(Date.parse(text))||new Date(text).toISOString().slice(0,10)!==text||Date.parse(text)>Date.now())){say(c,'请填写有效且不晚于今天的手术日期，格式 YYYY-MM-DD，例如 2026-09-01。');return;}c.fields[c.awaiting]=text;event(c,`已收集${labels[c.awaiting]}`);advance(c);return;}
 if(c.stage==='authorization-supplement'){c.fields.authorizationExtra=text;c.stage='authorization';c.status='等待保险确认';c.owner='保险专员';receipt(c,'authorization','授权补资料已提交','Front Desk AI','保险专员 · 模拟收件箱',{补充资料:text,申请轮次:c.authorizationRound||1},{处理:'已重新提交影像与康复授权申请'},'waiting');event(c,'患者补充授权资料 → 重新提交保险审核');say(c,'补充资料已提交，保险专员会重新审核 MRI / CT 与康复疗程申请。');return;}
 say(c,c.stage==='review'?'正在等待医疗审核，您的补充已记录。':c.stage==='insurance'?'正在等待保险确认。也可点击“自费继续”。':c.stage==='authorization'?'正在等待影像与康复授权结果。':c.stage==='authorization-appeal'?'医生申述任务已创建，等待医疗团队提交。':c.stage==='authorization-denied'?'当前授权未通过，可由医生发起申述。':c.stage==='authorization-done'?'授权已完成，可继续安排影像检查与康复疗程。':c.stage==='booked'?'预约已确认，可使用下方按钮改约或取消。':'请使用下方可预约时段完成选择。');}
export function startPostVisit(c,fields){Object.assign(c.fields,fields);c.intent='postvisit';c.insurance=true;c.stage='postvisit-ready';c.status='已完成看诊';c.owner='Front Desk AI';receipt(c,'doctor','医生看诊记录已完成','林悦医生','Front Desk Agent',{患者:c.name,病历:c.fields.visitNote,影像建议:c.fields.imaging,检查部位:c.fields.imagingSite,康复建议:c.fields.rehabPlan,康复申请路径:c.fields.rehabApplicant},{已接收:'客服可代为提交影像与康复授权申请'},'done');event(c,'医生完成看诊 → 病历与医嘱交给 Front Desk Agent');say(c,`医生已完成看诊记录：建议进行${c.fields.imaging}检查，并开始${c.fields.rehabVisits}次康复治疗。我们会先帮您向保险申请影像检查和康复治疗，保险回复后再联系您安排拍片、康复和医生读片时间。`);}
export function submitPostVisitAuthorization(c){if(c.stage!=='postvisit-ready')throw Error('当前不在看诊后授权准备状态');startAuthorization(c);}
function startAuthorization(c){c.authorizationRound=(c.authorizationRound||0)+1;c.authorizationStatus='pending';c.stage='authorization';c.status='等待保险确认';c.owner='保险专员';const common={患者:c.name,申请轮次:c.authorizationRound,保险公司:c.fields.company,保险计划:c.fields.plan,会员编号:c.fields.member};receipt(c,'authorization','影像检查授权申请','Front Desk Agent','保险授权审核',{...common,检查类型:c.fields.imaging,检查部位:c.fields.imagingSite,医疗必要性:c.fields.visitNote},{状态:'等待保险审核',下一步:'批准 / 补资料 / 拒绝 / 医生申述'},'waiting');receipt(c,'authorization','康复疗程授权申请','Front Desk Agent','保险授权审核',{...common,申请人:c.fields.rehabApplicant,申请次数:c.fields.rehabVisits,治疗计划:c.fields.rehabPlan,关联病历:c.fields.visitNote},{状态:'等待保险审核',下一步:'批准 / 补资料 / 拒绝 / 医生申述'},'waiting');event(c,`客服代办 → 同时提交 ${c.fields.imaging} 影像授权与 ${c.fields.rehabApplicant} 康复疗程授权`);say(c,`客服已根据医生病历提交影像检查（${c.fields.imaging}）和康复疗程（${c.fields.rehabVisits} 次）授权，正在等待保险回复。`);}
export function review(c,decision,note,provider){if(c.stage!=='review'||c.human)throw Error('当前不在可审核状态');if(!['accept','supplement','reject'].includes(decision))throw Error('未知审核操作');if(decision==='accept'&&!providers.some(p=>p.id===provider))throw Error('请选择有效接诊人员');if(!note.trim())throw Error('请填写审核意见或所需补充资料');doctorReply(c,decision,note,providers.find(p=>p.id===provider)?.name);event(c,`医疗审核：${decision}；意见：${note}`);say(c,`医疗审核意见：${note}`);if(decision==='reject'){c.review='rejected';c.stage='closed';c.status='已完成';c.owner='医疗审核组';say(c,'本机构暂不适合接诊，本次预约流程已结束。');return;}if(decision==='supplement'){c.review='supplement';delete c.fields.extra;advance(c);return;}c.review='accepted';c.matchedProvider=provider;advance(c);}
export function eligible(c,result){if(c.stage!=='insurance'||c.human)throw Error('当前不在保险确认状态');if(!['covered','unsupported','selfpay'].includes(result))throw Error('未知保险结果');const task=c.receipts?.findLast(r=>r.kind==='insurance'&&r.status==='waiting');if(task){task.status='done';task.response={处理:'已处理',结果:result};}receipt(c,'insurance','费用核验结果回传',result==='selfpay'?'患者':'保险专员','Front Desk AI',{选择:result},{下一步:result==='unsupported'?'等待患者决定自费或结束':c.insuranceFirst&&!c.visitConfirmed?'将核验结果返回患者，等待就诊决定':'解除费用门槛，继续排班'});c.eligibility=result;event(c,`费用确认 → ${result}`);if(result==='unsupported'){say(c,'保险专员确认不支持，请选择自费继续或结束会话。');return;}advance(c);}
export function authorize(c,result){if(!['authorization','authorization-supplement','authorization-denied'].includes(c.stage)||c.human)throw Error('当前不在授权审核状态');if(!['approved','supplement','denied','appeal'].includes(result))throw Error('未知授权结果');for(const r of c.receipts||[])if(r.kind==='authorization'&&r.status==='waiting'){r.status='done';r.response={...r.response,处理:'保险审核已返回',结果:result};}c.authorizationStatus=result;receipt(c,'authorization','保险授权结果回传','保险专员','Front Desk Agent',{申请轮次:c.authorizationRound,结果:result},{影像检查:c.fields.imaging,康复疗程:c.fields.rehabVisits+' 次',下一步:result==='approved'?'通知患者并安排后续':result==='supplement'?'补充病历或检查资料再提交':result==='denied'?'可由医生发起申述':'创建医生申述任务'});event(c,`保险授权结果 → ${result==='approved'?'批准':result==='supplement'?'需要补资料':result==='denied'?'拒绝':'医生申述'}`);if(result==='approved'){c.stage='authorization-done';c.status='等待预约';c.owner='Front Desk AI';beginPostVisitScheduling(c);return;}if(result==='supplement'){c.stage='authorization-supplement';c.status='等待补资料';c.owner='Front Desk AI';say(c,'保险需要补充病历或检查资料，请提交后重新申请。');return;}if(result==='denied'){c.stage='authorization-denied';c.status='授权未通过';c.owner='医疗审核组';say(c,'保险暂未批准本次申请。可以由医生整理病历并发起申述。');return;}c.stage='authorization-appeal';c.status='等待医生申述';c.owner='医疗审核组';receipt(c,'doctor','医生申述任务','Front Desk Agent','林悦医生',{患者:c.name,申请轮次:c.authorizationRound,保险结果:'需要医生申述',影像与康复申请:{影像:c.fields.imaging,康复次数:c.fields.rehabVisits}},{处理:'等待医生提交申述材料'},'waiting');say(c,'保险已返回“医生申述”，我已把病历和申请资料送到林悦医生的申述队列。');}
export function submitAppeal(c,note){if(!['authorization-appeal','authorization-denied'].includes(c.stage)||c.human)throw Error('当前没有可提交的医生申述');if(!note.trim())throw Error('请填写医生申述意见');const task=c.receipts?.findLast(r=>r.kind==='doctor'&&r.title==='医生申述任务'&&r.status==='waiting');if(task){task.status='done';task.response={处理:'医生申述已提交',意见:note,下一步:'等待保险重新审核'};}receipt(c,'authorization','医生申述已提交','林悦医生','保险授权审核',{申请轮次:c.authorizationRound,申述意见:note,影像检查:c.fields.imaging,康复疗程:c.fields.rehabVisits},{状态:'等待保险重新审核',可返回:'批准 / 补资料 / 拒绝'},'waiting');c.stage='authorization';c.status='等待保险确认';c.owner='保险专员';c.authorizationRound=(c.authorizationRound||0)+1;event(c,'医生完成申述 → 重新提交保险授权审核');say(c,'医生申述已提交，保险专员将重新审核影像和康复疗程申请。');}
+function postvisitDate(days,time){const d=new Date();d.setDate(d.getDate()+days);return d.toLocaleDateString('sv-SE')+' '+time;}
export function beginPostVisitScheduling(c){if(c.stage!=='authorization-done'||c.human)throw Error('当前不在可协调的看诊后服务状态');c.stage='postvisit-imaging';c.status='等待患者确认影像时间';c.owner='Front Desk AI';event(c,'保险已批准 → Agent 主动联系患者确认影像时间');say(c,`保险已批准${c.fields.imaging}检查和${c.fields.rehabVisits}次康复疗程。我们先安排影像检查，请选择方便的拍片时间；影像中心确认后，再安排医生读片和下一次康复。`);}
export function choosePostVisitSlot(c,type,slot){const expected={imaging:'postvisit-imaging',read:'postvisit-read',rehab:'postvisit-rehab'}[type];if(c.stage!==expected||c.human)throw Error('当前不在该预约环节');const labels={imaging:'影像检查',read:'医生读片 / 复诊',rehab:'下一次康复治疗'};const previous=c.postVisitAppointments||[];const item={类型:labels[type],时间:slot};receipt(c,'booking',labels[type]+'预约协调与确认','Front Desk Agent',type==='imaging'?'Mock 影像中心':type==='rehab'?'Mock 康复排班':'林悦医生',{患者:c.name,授权状态:c.authorizationStatus,预约项目:item},{结果:'已协调确认',顺序:type==='imaging'?'先完成影像，再读片与康复':type==='read'?'影像完成后医生读片，再安排康复':'完成本次串联预约'},'done');c.postVisitAppointments=[...previous,item];if(type==='imaging'){c.stage='postvisit-read';c.status='等待患者确认读片时间';c.owner='Front Desk AI';event(c,'影像中心已确认时间 → Agent 询问医生读片时间');say(c,`影像中心已确认${slot}。请先完成${c.fields.imaging}，然后选择医生读片 / 复诊时间。`);}else if(type==='read'){c.stage='postvisit-rehab';c.status='等待患者确认康复时间';c.owner='Front Desk AI';event(c,'医生读片时间已确认 → Agent 询问下一次康复时间');say(c,`医生读片 / 复诊时间已确认：${slot}。读片完成后，请选择下一次康复治疗时间。`);}else{c.stage='closed';c.status='已安排';c.owner='诊所前台';event(c,'康复时间已确认 → 影像、读片和康复串联安排完成');say(c,`已完成串联安排：${previous.map(x=>x.类型+' '+x.时间).join('；')}；${labels[type]} ${slot}。请按顺序先完成影像，再参加医生读片，之后进行下一次康复。`);}}
export function reportAuthorizationStatus(c){if(c.intent!=='postvisit')return;const status=c.authorizationStatus==='pending'?'影像和康复授权仍在保险审核中':c.authorizationStatus==='approved'?`影像和${c.fields.rehabVisits}次康复疗程已获保险批准，目前${c.stage==='authorization-done'?'等待确认影像时间':c.stage==='postvisit-imaging'?'等待确认影像时间':c.stage==='postvisit-read'?'影像已协调，等待确认医生读片时间':c.stage==='postvisit-rehab'?'读片已协调，等待确认康复时间':'正在安排后续时间'}`:c.authorizationStatus==='supplement'?'保险要求补充病历或检查必要性资料':c.authorizationStatus==='denied'?'保险暂未批准，可由医生发起申述':c.authorizationStatus==='appeal'?'保险要求医生申述，医疗团队正在准备':'尚未收到保险授权结果';event(c,'患者主动询问授权状态 → 返回当前申请结果');say(c,`当前进度：${status}。`);}
export function available(db,c){const p=c.matchedProvider||providers.find(p=>p.name===c.fields.provider)?.id;return db.slots.filter(s=>(!p||s.provider===p)&&!s.bookedBy);}
export function book(db,c,id){if(c.stage!=='slots'||c.human||c.risk)throw Error('预约条件未满足');const slot=available(db,c).find(s=>s.id===id);if(!slot)throw Error('该时段已不可用，请选择其他时段');const previous=c.appointment;if(c.appointment){const old=db.slots.find(s=>s.id===c.appointment);if(old)delete old.bookedBy;}slot.bookedBy=c.id;receipt(c,'booking',previous?'改约提交与确认':'预约提交与确认','Front Desk AI','Mock 预约系统',{患者:c.name,时段:id,原预约:previous||'无',医疗审核:c.review||'无需审核',费用:c.eligibility||'自费'},{预约编号:`YD-${c.number.toString().padStart(4,'0')}`,人员:providers.find(p=>p.id===slot.provider).name,日期:slot.date,时间:slot.time,结果:'预约成功',原时段:previous?'已释放':'不适用'});c.appointment=id;c.stage='booked';c.status='已预约';c.owner='诊所前台';say(c,`预约成功：${providers.find(p=>p.id===slot.provider).name} · ${slot.date} ${slot.time}。预约编号 YD-${c.number.toString().padStart(4,'0')}。`);event(c,'时段占用成功 → 预约确认已回传患者');}
export function reschedule(c){if(c.stage!=='booked'||c.human)throw Error('当前无法改约');c.stage='slots';c.status='AI处理中';say(c,'请选择新时段，确认成功前原预约继续保留。');event(c,'发起改约 → 保留原时段直至新时段确认');}
export function cancel(db,c){if(!c.appointment||c.human)throw Error('当前无法取消');const s=db.slots.find(s=>s.id===c.appointment);if(s)delete s.bookedBy;receipt(c,'booking','取消预约','患者 → Front Desk AI','Mock 预约系统',{原预约:c.appointment},{结果:'已取消',时段:'已释放'});c.appointment=null;c.stage='closed';c.status='已完成';say(c,'预约已取消，原时段已释放。');event(c,'取消预约 → 释放时段 → 结束 Case');}
export function handoff(c){if(c.human){if(c.risk)throw Error('请先由医疗人员确认风险已处理');c.human=false;for(const r of c.receipts||[])if(r.kind==='human'&&r.status==='waiting'){r.status='done';r.response={...r.response,处理:'人工已归还 AI'};}receipt(c,'human','人工归还 AI',c.owner,'Front Desk AI',{恢复节点:c.stage},{执行:'恢复原会话业务流程'});event(c,'人工归还 AI → 恢复原流程');if(['intro','collect','review','insurance','slots','insurance-decision','visit-intro'].includes(c.stage)){if(c.intent)advance(c);else{c.status='AI处理中';c.owner='Front Desk AI';say(c,'AI 已恢复，请描述就诊需求。');}}else{c.status=c.stage==='booked'?'已预约':'已完成';c.owner='诊所前台';}}else{c.human=true;c.status='等待人工';c.owner='人工客服';event(c,'人工主动接管 → AI 暂停');receipt(c,'human','人工接管任务','Front Desk AI',c.owner,fieldSnapshot(c),{处理:'等待人工回复',AI:'暂停自动回复'},'waiting');}}
export function resolveRisk(c,note){if(!c.risk||!note.trim())throw Error('请记录医疗处理结果');c.risk=false;event(c,`医疗人员确认风险已处理：${note}`);say(c,note,'staff');}
export const next=c=>c.human?'由责任人回复并处理':({intro:'描述就诊需求','insurance-decision':'患者决定是否继续就诊','visit-intro':'患者描述就诊需求',collect:`补充${labels[c.awaiting]}`,review:'医生接受 / 补资料 / 不适合',insurance:'人工核验或患者选择自费',authorization:'保险批准 / 补资料 / 拒绝 / 医生申述','authorization-supplement':'补充病历资料后重新提交','authorization-denied':'医生整理病历并发起申述','authorization-appeal':'医生提交申述材料','authorization-done':'确认影像时间','postvisit-imaging':'影像中心协调后确认时间','postvisit-read':'确认医生读片 / 复诊时间','postvisit-rehab':'确认下一次康复治疗时间','slots':'选择可预约时段',booked:'到诊 / 改约 / 取消',closed:'服务结束'})[c.stage];

export function querySchedule(db,c){if(c.stage!=='slots'||c.human)return;const slots=available(db,c);receipt(c,'schedule','查询可预约排班','Front Desk AI','Mock 排班工具',{匹配人员:providers.find(p=>p.id===c.matchedProvider)?.name||c.fields.provider||'全部可接诊人员',期望时间:c.fields.wish,过滤规则:'仅返回未占用时段；期望时间作偏好',医疗门槛:c.review||'无需审核',费用门槛:c.eligibility||'自费'},{可用数量:slots.length,时段:slots.map(s=>({人员:providers.find(p=>p.id===s.provider).name,日期:s.date,时间:s.time,时段ID:s.id})),后续:'患者选定 → 再次校验占用 → 创建预约'});}

function checkInsurance(c){ if(c.insurance&&!['covered','selfpay'].includes(c.eligibility)){if(!c.eligibility){c.eligibility=insuranceTool.check(c.fields.company,c.fields.plan);receipt(c,'insurance','保险资格查询','Front Desk AI','Mock 保险查询工具',{公司:c.fields.company,计划:c.fields.plan,会员编号:c.fields.member,服务:'运动医学 / 康复门诊',关联Case:c.id},{结果:({covered:'可覆盖',manual:'需人工确认',unsupported:'不支持'})[c.eligibility],结果代码:c.eligibility,依据:c.eligibility==='covered'?'演示规则：Aetna + International':c.eligibility==='unsupported'?'演示规则：Bupa 不支持':'演示规则：其他公司或计划交人工核验',额度:'Mock 未提供，不作真实费用承诺',下一步:c.eligibility==='covered'?(c.insuranceFirst&&!c.visitConfirmed?'先将保险结果返回患者，等待就诊决定':'继续查询排班'):'创建保险专员处理任务'});if(c.eligibility!=='covered')receipt(c,'insurance','保险专员处理任务','Front Desk AI','保险专员 · 模拟收件箱',{公司:c.fields.company,计划:c.fields.plan,查询结果:c.eligibility},{处理:'等待专员核验或患者选择自费'},'waiting');}event(c,`Mock eligibility → ${c.eligibility}`);if(c.eligibility!=='covered'){c.stage='insurance';c.status='等待保险确认';c.owner='保险专员';say(c,c.eligibility==='manual'?'模拟核验需要人工确认，已交保险专员处理。':'模拟核验：该计划不支持。您可以选择自费继续，或等待保险专员协助。');return true;}}return false;}

export function decideVisit(c,proceed){if(c.stage!=='insurance-decision'||c.human)throw Error('当前不在患者就诊决定环节');receipt(c,'decision','患者决定下一步','患者','Front Desk AI',{保险结果:c.eligibility,选择:proceed?'继续就诊':'暂不就诊'},{下一步:proceed?'询问就诊需求，再执行相应医疗流程':'结束保险咨询，不创建预约'});if(!proceed){c.stage='closed';c.status='已完成';c.owner='患者';say(c,'好的，本次仅完成保险咨询，没有创建预约。需要就诊时欢迎再联系。');event(c,'患者暂不就诊 → 结束咨询，不占用排班');return;}c.visitConfirmed=true;c.intent=null;c.stage='visit-intro';c.status='AI处理中';c.owner='Front Desk AI';say(c,'好的，保险查询结果已保留。请告诉我您目前的就诊需求，我再协助联系合适的医疗人员或安排预约。');event(c,'患者确认继续 → 开始就诊需求收集');}
