import {test} from 'node:test';import assert from 'node:assert/strict';import * as W from './workflow.js';
function setup(text){const db=W.initial(),c=W.create(db);W.receive(c,text);return {db,c};}
const answers={part:'膝盖',duration:'两周',treatment:'未治疗',wish:'下午',history:'活动受限',documents:'模拟病历与影像',surgeryDate:'2026-09-01',procedure:'ACLR',provider:'陈晨 PT',company:'Aetna',plan:'International',member:'DEMO-001',extra:'补充影像'};
function fill(c){let n=0;while(c.stage==='collect'&&n++<20)W.receive(c,answers[c.awaiting]);}
test('common booking → reschedule atomic release → cancellation',()=>{const {db,c}=setup('跑步膝痛');fill(c);assert.equal(c.stage,'slots');const [a,b]=W.available(db,c);W.book(db,c,a.id);W.reschedule(c);assert.equal(a.bookedBy,c.id);assert.throws(()=>W.book(db,c,'missing'));assert.equal(a.bookedBy,c.id);W.book(db,c,b.id);assert.equal(a.bookedBy,undefined);W.cancel(db,c);assert.equal(b.bookedBy,undefined);assert.equal(c.status,'已完成');});
test('postop blocked before review, supplemental loop and match',()=>{const {db,c}=setup('外院 ACLR 术后康复');fill(c);assert.equal(c.stage,'review');assert.throws(()=>W.book(db,c,db.slots[0].id));W.review(c,'supplement','请补影像','chen');assert.equal(c.awaiting,'extra');W.receive(c,'已补影像');assert.equal(c.stage,'review');W.review(c,'accept','可安排初评','chen');assert.ok(W.available(db,c).every(s=>s.provider==='chen'));W.book(db,c,W.available(db,c)[0].id);assert.equal(c.status,'已预约');});
test('uncertain case rejected cannot book',()=>{const {db,c}=setup('舟骨不愈合');fill(c);W.review(c,'reject','本机构资源不适合','lin');assert.equal(c.status,'已完成');assert.throws(()=>W.book(db,c,db.slots[0].id));});
test('insurance covered / manual / unsupported with selfpay',()=>{for(const [company,outcome]of [['Aetna','covered'],['Cigna','manual'],['Bupa','unsupported']]){const {db,c}=setup(`膝痛 ${company} 保险`);fill(c);assert.equal(c.eligibility,outcome);if(outcome!=='covered'){assert.throws(()=>W.book(db,c,db.slots[0].id));W.eligible(c,outcome==='manual'?'covered':'selfpay');}W.book(db,c,W.available(db,c)[0].id);assert.equal(c.status,'已预约');}});
test('provider selection and occupied slot protection',()=>{const {db,c}=setup('指定陈晨 PT');fill(c);assert.ok(W.available(db,c).every(s=>s.provider==='chen'));const slot=W.available(db,c)[0];W.book(db,c,slot.id);const other=W.create(db);W.receive(other,'指定陈晨 PT');fill(other);assert.throws(()=>W.book(db,other,slot.id));});
test('handoff suppresses AI; resume collection; risk requires staff resolution',()=>{const {db,c}=setup('膝痛');W.handoff(c);const count=c.messages.length;W.receive(c,'两周');assert.equal(c.messages.length,count+1);W.handoff(c);assert.equal(c.awaiting,'part');W.receive(c,'术后突然肿胀');assert.equal(c.risk,true);assert.throws(()=>W.handoff(c));assert.throws(()=>W.book(db,c,db.slots[0].id));W.resolveRisk(c,'医疗人员已联系患者并完成处理');W.handoff(c);assert.equal(c.human,false);});
test('complaint and unknown routing',()=>{let {c}=setup('我要投诉');assert.equal(c.human,true);assert.equal(c.owner,'人工客服');({c}=setup('一个不清楚的问题'));assert.equal(c.intent,'review');});
test('postop plus insurance requires both gates',()=>{const {c}=setup('ACLR 术后，有 Cigna 保险');fill(c);assert.equal(c.stage,'review');W.review(c,'accept','同意初评','chen');assert.equal(c.stage,'insurance');W.eligible(c,'covered');assert.equal(c.stage,'slots');});
test('invalid and future surgery dates rejected',()=>{const {c}=setup('术后康复');for(const date of ['2026-02-30','2099-01-01','昨天']){W.receive(c,date);assert.equal(c.fields.surgeryDate,undefined);}W.receive(c,'2026-09-01');assert.equal(c.fields.surgeryDate,'2026-09-01');});
test('doctor receipts retain each review round and request snapshots',()=>{const {c}=setup('ACLR 术后');fill(c);const first=c.receipts.find(r=>r.kind==='doctor');assert.equal(first.status,'waiting');assert.equal(first.request.已收集资料.extra,undefined);W.review(c,'supplement','补充影像','chen');W.receive(c,'补充新的影像');const tasks=c.receipts.filter(r=>r.kind==='doctor'&&r.title.startsWith('医疗审核任务'));assert.equal(tasks.length,2);assert.equal(tasks[0].status,'done');assert.equal(tasks[1].status,'waiting');assert.equal(tasks[0].request.已收集资料.extra,undefined);assert.equal(tasks[1].request.已收集资料.extra,'补充新的影像');W.review(c,'accept','同意','chen');assert.ok(tasks.every(r=>r.status==='done'));});
test('insurance request, tool response, manual return and schedule payload',()=>{const {db,c}=setup('膝痛 Cigna 保险');fill(c);const query=c.receipts.find(r=>r.title==='保险资格查询');assert.equal(query.request.公司,'Cigna');assert.equal(query.response.结果代码,'manual');assert.ok(c.receipts.some(r=>r.kind==='insurance'&&r.status==='waiting'));W.eligible(c,'covered');W.querySchedule(db,c);assert.ok(!c.receipts.some(r=>r.kind==='insurance'&&r.status==='waiting'));const schedule=c.receipts.find(r=>r.kind==='schedule');assert.equal(schedule.response.可用数量,W.available(db,c).length);const slot=W.available(db,c)[0];W.book(db,c,slot.id);assert.equal(c.receipts.find(r=>r.kind==='booking').response.结果,'预约成功');assert.ok(c.receipts.some(r=>r.kind==='message'&&r.request.消息.includes('预约成功')));});
test('insurance-first collects only insurance then waits for patient; decline never books',()=>{const {db,c}=setup('先查 Aetna 保险，再决定是否看诊');assert.equal(c.awaiting,'plan');fill(c);assert.equal(c.stage,'insurance-decision');assert.equal(c.fields.part,undefined);assert.equal(c.review,null);assert.equal(c.appointment,null);assert.throws(()=>W.book(db,c,db.slots[0].id));assert.ok(!c.receipts.some(r=>r.kind==='doctor'||r.kind==='schedule'));W.decideVisit(c,false);assert.equal(c.stage,'closed');assert.ok(db.slots.every(s=>!s.bookedBy));});
test('insurance-first continue with postop still requires medical review without requery',()=>{const {db,c}=setup('先查 Cigna 保险，再决定是否看诊');fill(c);assert.equal(c.stage,'insurance');W.eligible(c,'covered');assert.equal(c.stage,'insurance-decision');W.decideVisit(c,true);assert.equal(c.stage,'visit-intro');W.receive(c,'外院 ACLR 术后康复');fill(c);assert.equal(c.stage,'review');assert.throws(()=>W.book(db,c,db.slots[0].id));W.review(c,'accept','同意','chen');assert.equal(c.stage,'slots');assert.equal(c.receipts.filter(r=>r.title==='保险资格查询').length,1);});
